version: '3.3'
services:
  postgres:
    container_name: PostgreSQL
    restart: unless-stopped
    image: postgres
    environment: 
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - $DATABASE_PORT:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    container_name: Redis
    restart: unless-stopped
    image: redis
    ports:
      - $REDIS_PORT:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data: 
  redis-data:
