"""empty message

Revision ID: 348e21d4ee09
Revises: 
Create Date: 2022-01-29 08:09:46.191635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348e21d4ee09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
